title: Yawar Mohammad Khan
tagline: Senior Engineer Manager at Activision Blizzard
profile: /assets/img/yawar_pic.JPG
logo: /assets/img/yawar_logo.png
description: Senior Engineer Manager at Activision Blizzard
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: 'https://khanyawar.com'
