title: Yawar Mohammad Khan
tagline: Senior Engineer Manager at Activision Blizzard
logo: /assets/img/yawar_pic.jpg
description: Senior Engineer Manager at Activision Blizzard
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: 'https://khanyawar.com'
